default: &default
  adapter: postgresql
  encoding: unicode
  

development:
  <<: *default
  database: catalogo_filmes_development
  username: postgres 
  password: 123456

test:
  <<: *default
  database: catalogo_filmes_test


production:
  url: <%= ENV['DATABASE_URL'] %>
  
  adapter: postgresql